-- MySQL Script generated by MySQL Workbench
-- 09/07/14 22:08:42
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbl_tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_tipo_usuario` (
  `tip_usr_id` INT NOT NULL AUTO_INCREMENT,
  `tip_usr_desc` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`tip_usr_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_especialidad` (
  `esp_id` INT NOT NULL AUTO_INCREMENT,
  `esp_cod` VARCHAR(15) NOT NULL,
  `esp_nom` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`esp_id`),
  UNIQUE INDEX `esp_id_UNIQUE` (`esp_id` ASC),
  UNIQUE INDEX `esp_cod_UNIQUE` (`esp_cod` ASC),
  UNIQUE INDEX `esp_nom_UNIQUE` (`esp_nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_usuario` (
  `usr_id` INT NOT NULL AUTO_INCREMENT,
  `usr_cod` VARCHAR(15) NOT NULL,
  `tip_usr_id` INT NOT NULL,
  `usr_nom` VARCHAR(45) NOT NULL,
  `usr_apat` VARCHAR(30) NOT NULL,
  `usr_amat` VARCHAR(30) NOT NULL,
  `usr_dni` VARCHAR(8) NOT NULL,
  `usr_gen` TINYINT(1) NOT NULL,
  `usr_cel` VARCHAR(9) NOT NULL,
  `usr_mail` VARCHAR(40) NOT NULL,
  `usr_user` VARCHAR(20) NOT NULL,
  `usr_pass` TINYBLOB NOT NULL,
  `usr_est` TINYINT(1) NOT NULL,
  `esp_id` INT NOT NULL,
  PRIMARY KEY (`usr_id`),
  INDEX `fk_Usuario_TipoUsuario_idx` (`tip_usr_id` ASC),
  INDEX `fk_Usuario_Especialidad1_idx` (`esp_id` ASC),
  UNIQUE INDEX `usr_id_UNIQUE` (`usr_id` ASC),
  UNIQUE INDEX `usr_cod_UNIQUE` (`usr_cod` ASC),
  UNIQUE INDEX `usr_mail_UNIQUE` (`usr_mail` ASC),
  UNIQUE INDEX `usr_user_UNIQUE` (`usr_user` ASC),
  UNIQUE INDEX `usr_pass_UNIQUE` (`usr_pass` ASC),
  UNIQUE INDEX `usr_dni_UNIQUE` (`usr_dni` ASC),
  CONSTRAINT `fk_Usuario_TipoUsuario`
    FOREIGN KEY (`tip_usr_id`)
    REFERENCES `mydb`.`tbl_tipo_usuario` (`tip_usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Especialidad1`
    FOREIGN KEY (`esp_id`)
    REFERENCES `mydb`.`tbl_especialidad` (`esp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_curso` (
  `cur_id` INT NOT NULL AUTO_INCREMENT,
  `cur_cod` VARCHAR(15) NOT NULL,
  `cur_nom` VARCHAR(50) NOT NULL,
  `esp_id` INT NOT NULL,
  `cur_est` TINYINT(1) NOT NULL,
  PRIMARY KEY (`cur_id`),
  INDEX `fk_Curso_Especialidad1_idx` (`esp_id` ASC),
  UNIQUE INDEX `cur_id_UNIQUE` (`cur_id` ASC),
  UNIQUE INDEX `cur_cod_UNIQUE` (`cur_cod` ASC),
  CONSTRAINT `fk_Curso_Especialidad1`
    FOREIGN KEY (`esp_id`)
    REFERENCES `mydb`.`tbl_especialidad` (`esp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_sede` (
  `sed_id` INT NOT NULL AUTO_INCREMENT,
  `sed_desc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sed_id`),
  UNIQUE INDEX `sed_id_UNIQUE` (`sed_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_tipo_ambiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_tipo_ambiente` (
  `tip_amb_id` INT NOT NULL AUTO_INCREMENT,
  `tip_amb_den` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`tip_amb_id`),
  UNIQUE INDEX `tip_amb_id_UNIQUE` (`tip_amb_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_ambiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_ambiente` (
  `amb_id` INT NOT NULL AUTO_INCREMENT,
  `sed_id` INT NOT NULL,
  `amb_den` VARCHAR(15) NOT NULL,
  `tip_amb_id` INT NOT NULL,
  PRIMARY KEY (`amb_id`, `sed_id`),
  INDEX `fk_Ambiente_Sede1_idx` (`sed_id` ASC),
  INDEX `fk_Ambiente_TipoAmbiente1_idx` (`tip_amb_id` ASC),
  UNIQUE INDEX `amb_id_UNIQUE` (`amb_id` ASC),
  CONSTRAINT `fk_Ambiente_Sede1`
    FOREIGN KEY (`sed_id`)
    REFERENCES `mydb`.`tbl_sede` (`sed_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ambiente_TipoAmbiente1`
    FOREIGN KEY (`tip_amb_id`)
    REFERENCES `mydb`.`tbl_tipo_ambiente` (`tip_amb_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_tipo_Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_tipo_Servicio` (
  `tip_serv_id` INT NOT NULL AUTO_INCREMENT,
  `tip_serv_den` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`tip_serv_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_servicio_educativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_servicio_educativo` (
  `ser_edu_id` INT NOT NULL AUTO_INCREMENT,
  `ser_edu_fec` VARCHAR(45) NOT NULL,
  `ser_edu_hin` VARCHAR(45) NOT NULL,
  `cur_id` INT NOT NULL,
  `amb_id` INT NOT NULL,
  `sed_id` INT NOT NULL,
  `tip_serv_id` INT NOT NULL,
  `usr_adm_id` INT NOT NULL,
  `usr_tut_id` INT NOT NULL,
  `ser_edu_asist` TINYINT(1) NULL,
  PRIMARY KEY (`ser_edu_id`),
  INDEX `fk_ServicioEducativo_Curso1_idx` (`cur_id` ASC),
  INDEX `fk_ServicioEducativo_Ambiente1_idx` (`amb_id` ASC, `sed_id` ASC),
  INDEX `fk_ServicioEducativo_TipoServicio1_idx` (`tip_serv_id` ASC),
  INDEX `fk_ServicioEducativo_Usuario1_idx` (`usr_adm_id` ASC),
  INDEX `fk_ServicioEducativo_Usuario2_idx` (`usr_tut_id` ASC),
  CONSTRAINT `fk_ServicioEducativo_Curso1`
    FOREIGN KEY (`cur_id`)
    REFERENCES `mydb`.`tbl_curso` (`cur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ServicioEducativo_Ambiente1`
    FOREIGN KEY (`amb_id` , `sed_id`)
    REFERENCES `mydb`.`tbl_ambiente` (`amb_id` , `sed_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ServicioEducativo_TipoServicio1`
    FOREIGN KEY (`tip_serv_id`)
    REFERENCES `mydb`.`tbl_tipo_Servicio` (`tip_serv_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ServicioEducativo_Usuario1`
    FOREIGN KEY (`usr_adm_id`)
    REFERENCES `mydb`.`tbl_usuario` (`usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ServicioEducativo_Usuario2`
    FOREIGN KEY (`usr_tut_id`)
    REFERENCES `mydb`.`tbl_usuario` (`usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`tbl_alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_alumno` (
  `al_id` INT NOT NULL AUTO_INCREMENT,
  `al_cod` VARCHAR(15) NOT NULL,
  `al_nom` VARCHAR(45) NOT NULL,
  `al_apat` VARCHAR(30) NOT NULL,
  `al_amat` VARCHAR(30) NOT NULL,
  `al_cel` VARCHAR(9) NOT NULL,
  `al_mail` VARCHAR(40) NOT NULL,
  `al_susp` TINYINT(1) NOT NULL,
  PRIMARY KEY (`al_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_asistencia` (
  `ser_edu_id` INT NOT NULL,
  `al_id` INT NOT NULL,
  `ast_asist` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ser_edu_id`, `al_id`),
  INDEX `fk_ServicioEducativo_has_Alumno_Alumno1_idx` (`al_id` ASC),
  INDEX `fk_ServicioEducativo_has_Alumno_ServicioEducativo1_idx` (`ser_edu_id` ASC),
  CONSTRAINT `fk_ServicioEducativo_has_Alumno_ServicioEducativo1`
    FOREIGN KEY (`ser_edu_id`)
    REFERENCES `mydb`.`tbl_servicio_educativo` (`ser_edu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ServicioEducativo_has_Alumno_Alumno1`
    FOREIGN KEY (`al_id`)
    REFERENCES `mydb`.`tbl_alumno` (`al_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
